# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'iQuiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iQuiz
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'

  target 'iQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iQuizUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
